In [1]:
import pandas as pd
import xlrd
import numpy as np

io=r'AUs.xlsx'

AU= pd.read_excel(io, header=None)
print(AU.shape)
#print(df) 
#print(df.index)
#print(df.describe())

io=r'emotion3.xlsx'

emotion= pd.read_excel(io, header=None)
print(emotion.shape)


io=r'expression3.xlsx'

expression= pd.read_excel(io, header=None)
print(expression.shape)

(200, 30)
(200, 1)
(200, 1)


In [2]:
indtrain1=0
indtrain2=100

indtest1=101
indtest2=199

In [3]:
sample_train=AU[indtrain1:indtrain2]
label_train=emotion[indtrain1:indtrain2]
print(sample_train.shape)
print(label_train.shape)

sample_test=AU[indtest1:indtest2]
label_test=emotion[indtest1:indtest2]


(100, 30)
(100, 1)


In [4]:
from sklearn import svm
# 1. Initializing a SVM classifier, using linear kernel
clf = svm.SVC(kernel='poly',C=10.0,degree=3)
clf2 = svm.SVC(kernel='poly',C=10.0,degree=3)
# 2. using the classifier to fit your training data
clf.fit(sample_train, label_train)  
clf2.fit(sample_test, label_test)

C:\Users\yante\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\yante\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=10.0, kernel='poly')

In [5]:
# 1. Predicting you training data and testing data.
prediction_train = clf.predict(sample_train)
prediction = clf.predict(sample_test)

prediction_train2 = clf2.predict(sample_test)
prediction2 = clf2.predict(sample_train)

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
# 2. Calculating the accuracies of your prediction on training data and testing data, respectively.
#    2.1 calculate the accuracy when classifying the training data 
accuracy_training1 = accuracy_score(label_train,prediction_train)
print('accuracy_training1:',accuracy_training1)
#    2.2 calculate the accuracy when classifying the test data
accuracy_test1 = accuracy_score(label_test,prediction)
print('accuracy_test1:',accuracy_test1)

print('--------------------------------------------------------------------------')

accuracy_training2 = accuracy_score(label_test,prediction_train2)
print('accuracy_training2:',accuracy_training2)
#    2.2 calculate the accuracy when classifying the test data
accuracy_test2 = accuracy_score(label_train,prediction2)
print('accuracy_test2:',accuracy_test2)

accuracy_training1: 0.84
accuracy_test1: 0.3673469387755102
--------------------------------------------------------------------------
accuracy_training2: 0.9183673469387755
accuracy_test2: 0.42


In [6]:
sample_train=AU[indtrain1:indtrain2]
label_train=expression[indtrain1:indtrain2]
print(sample_train.shape)
print(label_train.shape)

sample_test=AU[indtest1:indtest2]
label_test=expression[indtest1:indtest2]

(100, 30)
(100, 1)


In [7]:
# 1. Initializing a SVM classifier, using linear kernel
clf = svm.SVC( kernel='poly',C=100.0,degree=4)  #   
clf2 = svm.SVC(kernel='poly',C=100.0,degree=4)
# 2. using the classifier to fit your training data
clf.fit(sample_train, label_train)  

clf2.fit(sample_test, label_test)

C:\Users\yante\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\yante\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=100.0, degree=4, kernel='poly')

In [8]:
# 1. Predicting you training data and testing data.
prediction_train = clf.predict(sample_train)
prediction = clf.predict(sample_test)


prediction_train2 = clf2.predict(sample_test)
prediction2 = clf2.predict(sample_train)

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
# 2. Calculating the accuracies of your prediction on training data and testing data, respectively.
#    2.1 calculate the accuracy when classifying the training data 
accuracy_training1 = accuracy_score(label_train,prediction_train)
print('accuracy_training1:',accuracy_training1)
accuracy_training2 = accuracy_score(label_train,prediction_train,normalize = False)


#    2.2 calculate the accuracy when classifying the test data
accuracy_test1 = accuracy_score(label_test,prediction)
print('accuracy_test1:',accuracy_test1)
accuracy_test2 = accuracy_score(label_test,prediction,normalize = False)

print('--------------------------------------------------------------------------')

accuracy_training2 = accuracy_score(label_test,prediction_train2)
print('accuracy_training2:',accuracy_training2)
#    2.2 calculate the accuracy when classifying the test data
accuracy_test2 = accuracy_score(label_train,prediction2)
print('accuracy_test2:',accuracy_test2)


accuracy_training1: 0.87
accuracy_test1: 0.5204081632653061
--------------------------------------------------------------------------
accuracy_training2: 0.9897959183673469
accuracy_test2: 0.52


In [9]:


from sklearn.metrics import confusion_matrix

# 3. Draw your confusion matrix
# 3. using sklearn.metrics.confusion_matrix
#    3.1 Calculate the confusion matrix when classifying the training data
confusion_training = confusion_matrix(label_train,prediction_train)
print(confusion_training)
print('--------------------------------------------------------------------------')

#    3.2 Calculate the confusion matrix when classifying the testing data
confusion_test = confusion_matrix(label_test,prediction)
print(confusion_test)
print('--------------------------------------------------------------------------')

print('train report:\n\n',classification_report(label_train,prediction_train),'\n\n')

print('test report:\n\n',classification_report(label_test,prediction))

[[38  0  0]
 [ 7 33  0]
 [ 4  2 16]]
--------------------------------------------------------------------------
[[24  1  9]
 [14 21  4]
 [18  1  6]]
--------------------------------------------------------------------------
train report:

               precision    recall  f1-score   support

           0       0.78      1.00      0.87        38
           1       0.94      0.82      0.88        40
           2       1.00      0.73      0.84        22

    accuracy                           0.87       100
   macro avg       0.91      0.85      0.87       100
weighted avg       0.89      0.87      0.87       100
 


test report:

               precision    recall  f1-score   support

           0       0.43      0.71      0.53        34
           1       0.91      0.54      0.68        39
           2       0.32      0.24      0.27        25

    accuracy                           0.52        98
   macro avg       0.55      0.49      0.49        98
weighted avg       0.59      0.52  